<?php
$_helper = $this->helper('Lof\MarketPlace\Helper\Data');
?>
<footer>
  <div class="pull-right">
  	<?php if($_helper->getConfig('design/footer_text')) {
  		echo $_helper->getConfig('design/footer_text');
  	} else { ?>
    	<?php echo __('Marketplace - Module by'); ?> <a href="http://landofcoder.com"><?php echo __('Landofcoder');?></a>
    <?php } ?>
  </div>
  <div class="clearfix"></div>
</footer>