<?php
$helper = $this->helper("Lof\MarketPlace\Helper\Data");
$data = $block->getSlider();

if($data):
	$image = json_decode($data["image_url"]);
	// $thumbnails = $block->resize($data["image_url"][0]->url_link, 400, 200);
?>
<div class="camera_wrap camera_magenta_skin" id="camera_wrap_2">
	<?php foreach ($image as $value): ?>
    <div data-link="<?php echo $value->url_link; ?>" data-target="_blank" data-src="<?php echo $helper->getMediaUrl() . $value->image_url; ?>">
        <div class="camera_caption fadeFromBottom">
            <?php echo $value->caption; ?>
        </div>
    </div>
    <?php endforeach;?>
</div>
<div style="clear:both; display:block; height:50px"></div>
<script type="text/javascript">

	requirejs([
		'require',
		'jquery',
		'jquery_Customized',
		'jquery_Easing',
		'Camera'
		],
            function (require, $, Camera) {
            	var image_height = '<?php echo $data["image_height"] ?>px';
				var slider_speed = '<?php echo $data["slider_speed"] ?>';
				var pagination = '<?php echo $data["pagination"] ?>';
				if(pagination == 1){
					pagination = true;
				}else{
					pagination = false;
				}
                jQuery('#camera_wrap_2').camera({
					height: image_height,
					loader: 'bar',
					pagination: pagination,
					thumbnails: false,
					time: slider_speed
				});
        	});
</script>
<?php endif;?>

