<?php
 $helper = $this->helper("Lof\MarketPlace\Helper\Data");

 $current_slider = $block->getSliderByID();
 $image_url = [];
 if(isset($current_slider["image_url"])){
 	$image_url = json_decode($current_slider["image_url"]);
 }
$effect = ['random','simpleFade', 'curtainTopLeft', 'curtainTopRight', 'curtainBottomLeft', 'curtainBottomRight', 'curtainSliceLeft', 'curtainSliceRight', 'blindCurtainTopLeft', 'blindCurtainTopRight', 'blindCurtainBottomLeft', 'blindCurtainBottomRight', 'blindCurtainSliceBottom', 'blindCurtainSliceTop', 'stampede', 'mosaic', 'mosaicReverse', 'mosaicRandom', 'mosaicSpiral', 'mosaicSpiralReverse', 'topLeftBottomRight', 'bottomRightTopLeft', 'bottomLeftTopRight', 'bottomLeftTopRight', 'scrollLeft', 'scrollRight', 'scrollHorz', 'scrollBottom', 'scrollTop'];
?>
<style type="text/css">
	img.image_show {max-width: 100%;}
	#list_image input{margin-top: 20px;}
</style>
<form data-mage-init='{"validation": {}}' class="entry-edit form-inline" action="<?php echo $block->getUrl('*/*/saveslider');?>" enctype="multipart/form-data" method="post" autocomplete="off">
	<?php
	if(isset($current_slider["slider_id"])){ ?>
		<input type="hidden" name="slider_id" class="admin__control-text" value="<?php echo $current_slider["slider_id"]; ?>" />
	<?php } ?>
	<input type="hidden" name="status" class="admin__control-text" value="0" />
	<div class="lof-mp-page-title page-title">
		<h2><?php echo (!$current_slider) ? __('Add New Slider') : __('Edit Slider')?></h2>
		<div class="page-actions-buttons">
			 <div class="actions-split save primary" title="Save">
				<button class="action-default primary" title="<?php echo __('Save ') ?>" type="submit">
					<span><span><?php echo __('Save Slider') ?></span></span>
				</button>
			</div>
		</div>
	</div>
	<div class="admin__fieldset-wrapper-content">
		<fieldset class="admin__fieldset">

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Title"); ?>
				</label>
				<div class="admin__field-control">
					<input type="text" value="<?php echo isset($current_slider['title'])? $current_slider['title'] : '' ?>" name="title" class="admin__control-text validate-no-html-tags"  />
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Image Types"); ?>
				</label>
				<div class="admin__field-control">
					<select class="admin__control-select" name="image_type" id="post_image_type">	
						<option value="1"><?php echo __("Upload") ?></option>
						<option value="2"><?php echo __("URL Link") ?></option>
					</select>
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Image upload"); ?>
				</label>

				<div class="admin__field-control" id="image">
			        <div class="row fileupload-buttonbar" id="image_upload">
			            <div class="col-lg-12">
			                <span class="btn btn-success fileinput-button">
			                    <i class="glyphicon glyphicon-plus"></i>
			                    <span><?php echo __("Add files...")?></span>
			                    <input type="file" name="file[]" class="<?php echo (!$current_slider)? 'required-file' : ''?>" multiple id="gallery-photo-add">
			                </span>
			                <button id="cancel_upload" type="button" class="btn btn-warning cancel'">
			                	<i class="glyphicon glyphicon-ban-circle"></i>
			                	<span><?php echo __("Cancel")?></span>
			                </button>
			            </div>
			        </div>
			        <!-- ========. image url .====== -->
					<div class="row fileupload-buttonbar" id="image_link">
			            <div class="col-lg-12">
			                <input type="text" id="image_link_input" name="image_link" placeholder="www.example/image.jpg" class="admin__control-text">
			            </div>
			        </div>
			        <!-- ========. image url .====== -->
			        <table  style="margin-top: 10px" role="presentation" id="list_image" class="table table-striped">
			        	<tbody>
			        		<?php foreach($image_url as $value): ?>
			        			<tr>
			        				<td>
			        					<image src="<?php echo $helper->getMediaUrl() . $value->image_url; ?>"/>
			        					<input type="text" value="<?php echo $value->caption; ?>" class="admin__control-text validate-no-html-tags" name="caption[]" placeholder="<?php echo __('Caption photo');?>"/>

						        		<input type="text" value="<?php echo $value->url_link; ?>" class="admin__control-text validate-url" name="url_link[]" placeholder="<?php echo __('Link URL');?>"/>
			        				</td>
			        			</tr>
							<?php endforeach;?>
			        	</tbody>
			        </table>
				</div>
			</div>


			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Show pagination :"); ?>
				</label>
				<div class="admin__field-control">
					<select class="admin__control-select" name="pagination">
						<option value="0" <?php echo ($current_slider['pagination'])? "selected" : ""?>>No</option>
						<option value="1" <?php echo ($current_slider['pagination'])? "selected" : ""?>>Yes</option>
					</select>
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Show thumbnails :"); ?>
				</label>
				<div class="admin__field-control">
					<select class="admin__control-select" name="thumbnail">
						<option value="0" <?php echo ($current_slider['thumbnail'])? "selected" : ""?>>No</option>
						<option value="1" <?php echo ($current_slider['thumbnail'])? "selected" : ""?>>Yes</option>
					</select>
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Effect slider :"); ?>
				</label>
				<div class="admin__field-control">
					<select class="admin__control-select" name="effect">
					<?php foreach($effect as $value): ?>
						<option value="<?php echo $value;?>" <?php echo ($current_slider['effect'] == $value)? "selected" : ""?>><?php echo $value;?></option>
					<?php endforeach; ?>
					</select>
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Image Height (in 'px') :"); ?><span style="color:red">*</span>
				</label>
				<div class="admin__field-control">
					<input type="text" name="image_height" value="<?php echo isset($current_slider['image_height'])? $current_slider['image_height'] : '' ?>" placeholder="<?php echo __('The height of slider');?>" class="admin__control-text required validate-number" />
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Slider Speed (in 'milliseconds') :"); ?><span style="color:red">*</span>
				</label>
				<div class="admin__field-control">
					<input type="text" name="slider_speed" value="<?php echo isset($current_slider['slider_speed'])? $current_slider['slider_speed'] : '' ?>" placeholder="<?php echo __('milliseconds between the end of the sliding effect and the start of the nex one')?>" class="admin__control-text required validate-number" />
				</div>
			</div>

			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Slider Duration (in 'milliseconds') :"); ?><span style="color:red">*</span>
				</label>
				<div class="admin__field-control">
					<input type="text" name="slider_duration" value="<?php echo isset($current_slider['slider_duration'])? $current_slider['slider_duration'] : '' ?>" class="admin__control-text required validate-number" placeholder="<?php echo __('length of the sliding effect in milliseconds')?>"/>
				</div>
			</div>
			<div class="admin__field">
				<label class="admin__field-label">
					<?php echo __("Set As Default Slider :"); ?>
				</label>
				<div class="admin__field-control">
					<select class="admin__control-select" name="is_active">
						<option value="0" <?php echo ($current_slider['is_active'])? "selected" : ""?>>No</option>
						<option value="1" <?php echo ($current_slider['is_active'])? "selected" : ""?>>Yes</option>
					</select>
				</div>
			</div>
			<input type="hidden" name="seller_id" value="<?php echo $helper->getSellerId(); ?>">
			<?php if(isset($current_slider["image_url"])){
				foreach($image_url as $value): ?>
				<input type="hidden" name="photo[]" value="<?php echo $value->image_url; ?>"/>
			<?php
			endforeach;
			} ?>
		</fieldset>
	</div>

</form>
<script>
	require(['jquery'], function(){
		var imagesPreview = function(input, placeToInsertImagePreview) {
	        if (input.files) {
	            var filesAmount = input.files.length;
	            for (i = 0; i < filesAmount; i++) {
	                var reader = new FileReader();
	                reader.onload = function(event) {
	                	jQuery("#list_image").find('tbody')
						    .append(jQuery('<tr>')
						        .append(jQuery('<td>')
						            .append(jQuery('<img>')
						                .attr('src', event.target.result).attr('class', 'image_show')
						                .text('Image cell')
						            )
						            .append(`
										<input type="text" value="" class="admin__control-text" name="caption[]" placeholder="Caption photo"/>
						        		<input type="text" value="" class="admin__control-text" name="url_link[]" placeholder="Link URL"/>
						            `)
						        )
						    )
	                	}
	                reader.readAsDataURL(input.files[i]);
	            }
	        }
    	};
    	// -------------------. Use url link

    	jQuery("#post_image_type").on("change", function(){
	        var val = jQuery(this).val();
	        if(val == "1"){
	            jQuery("#image_upload").show();
	            jQuery("#image_link").hide();
	        }else{
	            jQuery("#image_upload").hide();
	            jQuery("#image_link").show();
	        }
	    }).change();

	    //check image
	    function imageExists(url, callback) {
		    var img = new Image();
		    img.onload = function() { callback(true); };
		    img.onerror = function() { callback(false); };
		    img.src = url;
		}
		jQuery("#image_link_input").focusout(function(){
	      	var imageUrl = jQuery(this).val();
	      	imageExists(imageUrl, function(exists) {
	        	//Show the result
		        if (imageUrl !== '') {
		        	if (exists) {
		        		jQuery("#list_image").find('tbody')
					    .append(jQuery('<tr>')
					        .append(jQuery('<td>')
					            .append(jQuery('<img>')
					                .attr('src', imageUrl).attr('class', 'image_show')
					                .text('Image cell')
					            )
					            .append(`
									<input type="text" value="" class="admin__control-text" name="caption[]" placeholder="Caption photo"/>
					        		<input type="text" value="" class="admin__control-text" name="url_link[]" placeholder="Link URL"/>
					        		<a id="add_image_link" href="javascript:Void(0)">Add more</a>
					            `)
					        )
					    )
		        	}else{
		        		alert("Cannot found image");
		        	}
		        }else{
		        	jQuery("#list_image").find('tbody').empty();
		        }
        	})
	      });

    	// =================================

	    jQuery('#gallery-photo-add').on('change', function() {
	    	var extension = jQuery(this).val().split('.').pop();
	    	extension = extension.toLowerCase();
	    	var names_arr = ['jpg','jpeg','png'];
	    	if(names_arr.indexOf(extension) != -1){
	    		jQuery("#list_image").find('tbody').empty();
	        	imagesPreview(this, '#list_image');
	    	}else{
	    		alert("Please select image file");
	    		jQuery("#list_image").find('tbody').empty();
	    		jQuery(this).val() = '';
	    		return false;
	    	}
	    });
	    jQuery('#cancel_upload').on('click', function() {
	    	jQuery("#list_image").find('tbody').empty();
	        jQuery("#gallery-photo-add").val("");
	    });
	})
</script>
