<?php
	$data = $block->getSlider()->setOrder('slider_id', 'desc')->getData();
?>
<div class="page-title">
  <div class="title_left">
    <h3><?php echo __('Sliders'); ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'All Slider'; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
		        <table id="datatable" class="table table-striped table-bordered">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"> </th>
			                <th class="column-title"><?php echo __('Id');?> </th>
			                <th class="column-title"><?php echo __('Slider Title');?> </th>
			                <th class="column-title"><?php echo __('Status');?> </th>
			                <th class="column-title"><?php echo __('Created At'); ?> </th>
			                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
			                </th>
			                <th class="bulk-actions" colspan="7">
			                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
			                </th>
			          	</tr>
			        </thead>
			        <tbody>
				         <?php foreach ($data as $key => $slider) { ?>
				         <tr>
				         	<td class="hidden"> </td>
				         	<td class=""><?php echo $slider['slider_id']; ?>  </td>
				         	<td class=""><?php echo $slider['title']; ?>  </td>
				         	<td class=""><?php echo ($slider['is_active'] == 1)? 'Enabled' :'Disabled'; ?></td>
				         	<td class=""><?php echo $slider['created_at']; ?>  </td>
				         	<td class=" last"><a href="<?php echo $block->getUrl('catalog/slider/edit?slider_id='.$slider['slider_id']); ?>"><?php echo __('Edit'); ?></a>
				         </tr>
				         <?php } ?>
			        </tbody>
		        </table>
	      	</div>
	    </div>
    </div>
 </div>

