<?php
	$helper = $this->helper("Lof\MarketPlace\Helper\Data");
?>
<div class="page-title">
  <div class="title_left">
    <h3><?php echo __('Coupon Code'); ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'All Coupon Code'; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
	      		<form data-mage-init='{"validation": {}}' class="entry-edit form-inline" action="<?php echo $block->getUrl('*/*/generate');?>" enctype="multipart/form-data" method="post" autocomplete="off">
	      			<div class="row" style="margin-bottom: 10px">
		      			<div class="col-md-2"></div>
		      			<div class="col-md-3">
		      				<div class="admin__field-control">
								<input type="text" name="email" class="admin__control-text"  />
							</div>
		      			</div>
		      			<div class="col-md-2 text-center">
		      				<div class="admin__field-control">
								<select class="admin__control-select" style="padding-top: 0.6rem; padding-bottom: 0.6rem" name="rule_id">
									<option value="6">Rule name</option>
								</select>
							</div>
		      			</div>
	      				<div class="primary" title="Save">
							<button class="action-default primary" title="Save " type="submit">
								<span><span>Generate Coupon</span></span>
							</button>
						</div>
		      		</div>
	      			<input type="hidden" name="seller_id" value="<?php echo $helper->getSellerId(); ?>">
	      		</form>
		        <table id="datatable" class="table table-striped table-bordered">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"> </th>
			                <th class="column-title"><?php echo __('Id');?> </th>
			                <th class="column-title"><?php echo __('Coupon Code');?> </th>
			                <th class="column-title"><?php echo __('Status');?> </th>
			                <th class="column-title"><?php echo __('Created At'); ?> </th>
			                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
			                </th>
			                <th class="bulk-actions" colspan="7">
			                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
			                </th>
			          	</tr>
			        </thead>
			        <tbody>
				        <tr>
				        	<td class="hidden"> </td>
				         	<td class="">1</td>
				         	<td class="">2</td>
				         	<td class="">3</td>
				         	<td class="">4</td>
				         	<td class="last text-center">5</td>
				        </tr>
			        </tbody>
		        </table>
	      	</div>
	    </div>
    </div>
 </div>


